version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgredb
    environment:
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: restapi
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
    driver: local